"""애플리케이션 기본 설정."""

import os
from pathlib import Path


CAMERA_INDEX = 0
DEFAULT_FRAME_WIDTH = 640
DEFAULT_FRAME_HEIGHT = 480
WINDOW_TITLE = "Jetson Vision Tracker - Nano Pose + ReID"

AI_ROOT = Path(__file__).resolve().parents[1]
YUNET_MODEL_PATH = AI_ROOT / "models" / "face_detection_yunet_2023mar.onnx"
YUNET_SCORE_THRESHOLD = 0.8
YUNET_NMS_THRESHOLD = 0.3
YUNET_TOP_K = 5000

SFACE_MODEL_PATH = AI_ROOT / "models" / "face_recognition_sface_2021dec.onnx"

# 다중 인물 Pose와 ByteTrack
POSE_ENGINE_PATH = AI_ROOT / "models" / "yolo11n-pose.engine"
POSE_MODEL_PATH = POSE_ENGINE_PATH if POSE_ENGINE_PATH.is_file() else AI_ROOT / "models" / "yolo11n-pose.pt"
POSE_CONFIDENCE = 0.35
POSE_IMAGE_SIZE = 640
POSE_DEVICE = os.environ.get("VISION_POSE_DEVICE") or None
PERSON_REID_THRESHOLD = 0.86
PERSON_REID_MARGIN = 0.06
PERSON_LOST_TIMEOUT_SECONDS = 3.0

# 얼굴 중심 추적과 팬·틸트 각도 계산
PAN_INITIAL_ANGLE = 90
TILT_INITIAL_ANGLE = 90
PAN_MIN_ANGLE = 0
PAN_MAX_ANGLE = 180
TILT_MIN_ANGLE = 0
TILT_MAX_ANGLE = 180
PAN_INVERTED = True
TILT_INVERTED = True
TRACKING_FILTER_ALPHA = 0.15
TRACKING_DEAD_ZONE_RATIO = 0.12
TRACKING_GAIN = 6.0
TRACKING_MAX_STEP_DEGREES = 4.0
SERVO_SEND_INTERVAL_SECONDS = 0.1

# Jetson -> STM32 UART. 실제 장치명이 다르면 VISION_UART_PORT로 변경 가능.
UART_PORT = os.environ.get("VISION_UART_PORT", "/dev/ttyACM0")
UART_BAUD_RATE = 115200
UART_WRITE_TIMEOUT_SECONDS = 1
UART_RETRY_INTERVAL_SECONDS = 2.0

PACKET_HEADER = 0xAA
PACKET_TAIL = 0x55
PAN_TARGET_ID = 0x01
TILT_TARGET_ID = 0x02
SET_ANGLE_ACTION = 0x01

# 실시간 화면 캡처
CAPTURE_DEFAULT_DIR = AI_ROOT / "captures"
CAPTURE_FLASH_MILLISECONDS = 250
