"""애플리케이션 기본 설정."""

import os
from pathlib import Path


CAMERA_INDEX = 0
DEFAULT_FRAME_WIDTH = 640
DEFAULT_FRAME_HEIGHT = 480
WINDOW_TITLE = "Jetson Vision Tracker - YOLO Person + ReID"

AI_ROOT = Path(__file__).resolve().parents[1]
# YOLO class 0(person) 검출과 ByteTrack
PERSON_ENGINE_PATH = AI_ROOT / "models" / "yolo11n-person.engine"
PERSON_MODEL_PATH = PERSON_ENGINE_PATH if PERSON_ENGINE_PATH.is_file() else AI_ROOT / "models" / "yolo11n.pt"
PERSON_CONFIDENCE = 0.35
PERSON_IMAGE_SIZE = 640
PERSON_DEVICE = os.environ.get("VISION_PERSON_DEVICE") or None
PERSON_REID_THRESHOLD = 0.86
PERSON_REID_MARGIN = 0.06
PERSON_LOST_TIMEOUT_SECONDS = 3.0

# 인물 박스 안전 영역 기반 팬·틸트 제어
PAN_INITIAL_ANGLE = 0
TILT_INITIAL_ANGLE = 0
PAN_MIN_ANGLE = 0
PAN_MAX_ANGLE = 180
TILT_MIN_ANGLE = 0
TILT_MAX_ANGLE = 180
PAN_INVERTED = True
TILT_INVERTED = True
TRACKING_FILTER_ALPHA = 0.15
TRACKING_GAIN = 6.0
TRACKING_MAX_STEP_DEGREES = 2.0
TRACKING_BOX_HISTORY_SIZE = 3
TRACKING_BOUNDARY_CONFIRM_FRAMES = 3
TRACKING_PAN_CONFIRM_FRAMES = 2
TRACKING_TILT_CONFIRM_FRAMES = 3
TRACKING_SETTLE_SECONDS = 0.3
TRACKING_PAN_START_MARGIN = 0.22
TRACKING_PAN_RELEASE_MARGIN = 0.30
TRACKING_HEAD_BOX_RATIO = 0.10
TRACKING_HEAD_START_TOP = 0.22
TRACKING_HEAD_START_BOTTOM = 0.42
TRACKING_HEAD_RELEASE_TOP = 0.28
TRACKING_HEAD_RELEASE_BOTTOM = 0.36
SERVO_SEND_INTERVAL_SECONDS = 0.1

# Jetson -> STM32 UART. 실제 장치명이 다르면 VISION_UART_PORT로 변경 가능.
UART_PORT = os.environ.get("VISION_UART_PORT", "/dev/ttyACM0")
UART_BAUD_RATE = 115200
UART_WRITE_TIMEOUT_SECONDS = 1
UART_RETRY_INTERVAL_SECONDS = 2.0

PACKET_HEADER = 0xAA
PACKET_TAIL = 0x55
PAN_TARGET_ID = 0x01
TILT_TARGET_ID = 0x02
SET_ANGLE_ACTION = 0x01

# 실시간 화면 캡처
CAPTURE_DEFAULT_DIR = AI_ROOT / "captures"
CAPTURE_FLASH_MILLISECONDS = 250
